
DROP TABLE answer_to_criterion;;

DROP TABLE answer;;

DROP TABLE study_case;;

DROP TABLE prerequisite;;

DROP TABLE criterion;;

DROP TABLE category;;

DROP TABLE reviewer;;


CREATE TABLE reviewer
(
    id INT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR (50) NOT NULL,
    login varchar(15) NOT NULL,
    password varchar(150) NOT NULL,
    admin BOOLEAN DEFAULT FALSE,
    full_review BOOLEAN DEFAULT FALSE,
    remaining_cases INT NOT NULL,
    PRIMARY KEY (id)
);;

CREATE TABLE category
(
    id INT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL,
    type INT NOT NULL,
    has_tutorial BOOLEAN DEFAULT FALSE,
    has_trust BOOLEAN DEFAULT FALSE,
    has_na BOOLEAN DEFAULT FALSE,
    optional BOOLEAN DEFAULT FALSE,
    has_gold_standard BOOLEAN DEFAULT FALSE,
    has_malignancy BOOLEAN DEFAULT FALSE,
    PRIMARY KEY (id)
);;

CREATE TABLE criterion
(                  
    id INT GENERATED BY DEFAULT AS IDENTITY,                                                  
    name VARCHAR(100) NOT NULL,                                              
    tutorial_path VARCHAR(200) NOT NULL,                                              
    category INT NOT NULL,
    is_trust BOOLEAN DEFAULT FALSE,
    malignancy BOOLEAN DEFAULT FALSE,
    PRIMARY KEY (id),
    FOREIGN KEY (category) REFERENCES category(id)
);;

CREATE TABLE prerequisite
(
    category INT NOT NULL,
    criterion INT NOT NULL,
    PRIMARY KEY (category, criterion),
    FOREIGN KEY (category) REFERENCES category(id),
    FOREIGN KEY (criterion) REFERENCES criterion(id)
);;

CREATE TABLE study_case
(
    id INT GENERATED BY DEFAULT AS IDENTITY,
    path VARCHAR(100) NOT NULL,
    name VARCHAR(10) NOT NULL,
    gold_standard INT NULL,
    PRIMARY KEY(id),
    FOREIGN KEY (gold_standard) REFERENCES criterion(id)
);;

CREATE TABLE answer
(                  
    id INT GENERATED BY DEFAULT AS IDENTITY,
    study_case INT NOT NULL,                                                  
    reviewer INT NOT NULL,     
    name VARCHAR (10) NOT NULL,                                       
    completed BOOLEAN DEFAULT FALSE,
    remarks VARCHAR(2000),
    PRIMARY KEY (id),
    FOREIGN KEY (study_case) REFERENCES study_case(id),
    FOREIGN KEY (reviewer) REFERENCES reviewer(id)
);;

CREATE TABLE answer_to_criterion
(
    answer INT NOT NULL,
    criterion INT NOT NULL,
    value INT NOT NULL DEFAULT 0,
    PRIMARY KEY (answer, criterion),
    FOREIGN KEY (answer) REFERENCES answer(id),
    FOREIGN KEY (criterion) REFERENCES criterion(id)
);;


INSERT INTO reviewer (name, login, password, admin, remaining_cases) VALUES ('Original Admin', 'admin', '$2b$12$H0P2muE8yXwdHBXMmIbo7uJ//6fl.a4PoFAKjf1ubhZNq0reyI1WG', true, 0);;
INSERT INTO reviewer (name, login, password, admin, remaining_cases) VALUES ('Test User', 'test', '$2b$12$H0P2muE8yXwdHBXMmIbo7uJ//6fl.a4PoFAKjf1ubhZNq0reyI1WG', false, 0);;
